// Explicitly switch to the operational database because of the 'bitnami/mongodb' image issue
db = typeof process == 'undefined' ? db : db.getSiblingDB(process.env["MONGODB_DATABASE"]);


// Populate 'Items' collection

db.Items.insertMany([

    // -- Laptops ('laptops') category items

    {
        _id: UUID('98759e19-e09c-4d5f-8115-f69d935934ee'),
        label: "Dell XPS 15 9500",
        category: "laptops",
        producer: "Dell",
        price: NumberDecimal('45999.00'),
        stock: 10,
        info: "The Dell XPS 15 9500 is a powerful laptop designed for professionals and enthusiasts.",
        specs: {
            CPU: "Intel Core i7-10750H",
            GPU: "Discrete, NVIDIA GeForce GTX 1650 Ti",
            RAM: "DDR4 16GB",
            SSD: "512GB PCIe NVMe",
            HDD: null,
            display: "15.6\" 4K UHD+ InfinityEdge Touch",
            multimedia: "720p HD webcam, Dual array microphones, Stereo speakers with Waves MaxxAudio Pro",
            wireless: ["Bluetooth 5.1", "Wi-Fi 6"],
            connectors: "2x Thunderbolt 3, 1x USB-C 3.1, 1x SD card reader",
            OS: "Windows 10 Pro",
            battery: "86Whr, Up to 12 hours",
            features: ["Fingerprint reader", "Backlit keyboard"],
            size: {length: 344, width: 230, height: 18},
            weight: 1940,
            color: "Platinum Silver with Black carbon fiber palmrest",
            equipment: "AC adapter, User documentation"
        },
        guarantee: 365
    },
    {
        _id: UUID('bcbab644-588a-453a-8e76-bc357ec771f2'),
        label: "MacBook Air M1",
        category: "laptops",
        producer: "Apple",
        price: NumberDecimal('39999.00'),
        stock: 8,
        info: "The MacBook Air M1 is the thinnest and lightest MacBook ever, yet it's still powerful.",
        specs: {
            CPU: "Apple M1 chip",
            GPU: "Integrated, Apple M1 chip",
            RAM: "8GB unified memory",
            SSD: "256GB PCIe-based SSD",
            HDD: null,
            display: "13.3\" Retina display with True Tone",
            multimedia: "720p FaceTime HD camera, Three-microphone array, Stereo speakers with wide stereo sound",
            wireless: ["Bluetooth 5.0", "Wi-Fi 6"],
            connectors: "2x Thunderbolt 3",
            OS: "macOS Big Sur",
            battery: "49.9Whr, Up to 15 hours",
            features: ["Touch ID", "Backlit Keyboard"],
            size: {length: 304, width: 212, height: 16},
            weight: 1290,
            color: "Space Gray",
            equipment: "USB-C power adapter, USB-C charge cable (2m)"
        },
        guarantee: 365
    },
    {
        _id: UUID('0415ea20-31cc-40f4-886f-c7581980d13b'),
        label: "Lenovo Legion 5",
        category: "laptops",
        producer: "Lenovo",
        price: NumberDecimal('28999.00'),
        stock: 6,
        info: "The Lenovo Legion 5 is a gaming laptop with powerful performance and great cooling.",
        specs: {
            CPU: "AMD Ryzen 7 4800H",
            GPU: "Discrete, NVIDIA GeForce GTX 1660 Ti",
            RAM: "DDR4 16GB",
            SSD: "512GB NVMe SSD",
            HDD: "1TB 7200rpm HDD",
            display: "15.6\" FHD IPS 144Hz",
            multimedia: "720p HD camera, Dual speakers with Nahimic 3D Audio",
            wireless: ["Bluetooth 5.0", "Wi-Fi 6"],
            connectors: "4x USB 3.1, 1x HDMI 2.0, 1x RJ45 Ethernet, 1x USB-C",
            OS: "Windows 10 Home",
            battery: null,
            features: ["Backlit keyboard", "Harman Kardon speakers"],
            size: {length: 363, width: 260, height: 24},
            weight: 2300,
            color: "Phantom Black",
            equipment: "230W AC adapter, Quick start guide"
        },
        guarantee: 365
    },
    {
        _id: UUID('ce8e362b-7d70-4ee8-accf-14e0152c3721'),
        label: "HP Spectre x360",
        category: "laptops",
        producer: "HP",
        price: NumberDecimal('54999.00'),
        stock: 5,
        info: "The HP Spectre x360 is a versatile convertible laptop with stunning design and performance.",
        specs: {
            CPU: "Intel Core i7-1165G7",
            GPU: "Intel Iris Xe Graphics",
            RAM: "DDR4 16GB",
            SSD: "1TB PCIe NVMe M.2 SSD",
            HDD: null,
            display: "13.3\" 4K OLED touchscreen",
            multimedia: "HP TrueVision HD IR camera, Dual array digital microphones, Bang & Olufsen speakers",
            wireless: ["Bluetooth 5.2", "Wi-Fi 6"],
            connectors: "2x Thunderbolt 4, 1x USB-A, 1x microSD card reader",
            OS: "Windows 11 Home",
            battery: "4-cell, 66Whr, Up to 16.5 hours",
            features: ["Fingerprint reader", "Backlit keyboard", "HP Pen support"],
            size: {length: 306, width: 194, height: 17.6},
            weight: 1290,
            color: "Nightfall Black with Copper Luxe accents",
            equipment: "USB-C to USB-C cable, HP Pen, Documentation"
        },
        guarantee: 365
    },

    // -- Mobile phones ('mobile-phones') category items

    {
        _id: UUID('f1f1e9d2-8865-4879-96a8-3fa98cacc216'),
        label: "Samsung Galaxy S22 Ultra",
        category: "mobile-phones",
        producer: "Samsung",
        price: NumberDecimal('34999.00'),
        stock: 15,
        info: "The Samsung Galaxy S22 Ultra is a flagship smartphone with top-notch features and performance.",
        specs: {
            CPU: "Exynos 2200",
            RAM: 12,
            sdCard: "MicroSDXC (uses shared SIM slot), up to 1TB",
            storage: 256,
            display: "6.8\" Dynamic AMOLED 2X, 120Hz",
            mainCam: "108MP+12MP+12MP+12MP, OIS, 100x Space Zoom",
            frontCam: "40MP, Dual Pixel AF",
            sensors: ["Accelerometer", "Gyroscope", "Proximity", "Compass"],
            navigation: "GPS, Galileo, Glonass, BDS",
            communication: ["5G", "LTE"],
            SIM: "Dual SIM (Nano-SIM and eSIM)",
            wireless: ["Bluetooth 5.2", "Wi-Fi 6E"],
            connectors: "USB Type-C 3.2",
            OS: "Android 12 with One UI 5.1",
            battery: "5000mAh, Up to 2 days",
            features: ["IP68 water/dust resistant", "Wireless DeX", "S Pen support"],
            size: {length: 166.3, width: 77.7, height: 8.9},
            weight: 228,
            color: "Phantom Black",
            equipment: "USB-C cable, Ejection pin, Quick start guide"
        },
        guarantee: 365
    },
    {
        _id: UUID('f509d521-b18b-4635-bc48-0754b9e36e4d'),
        label: "iPhone 13 Pro Max",
        category: "mobile-phones",
        producer: "Apple",
        price: NumberDecimal('43999.00'),
        stock: 20,
        info: "The iPhone 13 Pro Max is Apple's flagship smartphone with cutting-edge technology " +
              "and impressive camera capabilities.",
        specs: {
            CPU: "A15 Bionic chip",
            RAM: null,
            sdCard: null,
            storage: 512,
            display: "6.7\" Super Retina XDR OLED, ProMotion, HDR10",
            mainCam: "12MP (wide) + 12MP (ultra-wide) + 12MP (telephoto), Night mode, Deep Fusion",
            frontCam: "12MP TrueDepth, Night mode, Deep Fusion",
            sensors: ["Face ID", "Accelerometer", "Gyroscope", "Proximity", "Barometer", "LiDAR scanner"],
            navigation: "GPS, GLONASS, Galileo, QZSS",
            communication: ["5G", "LTE"],
            SIM: "Dual SIM (Nano-SIM and eSIM)",
            wireless: ["Bluetooth 5.0", "Wi-Fi 6"],
            connectors: "Lightning",
            OS: "iOS 15",
            battery: "4352mAh, Up to 28 hours talk time",
            features: ["IP68 water/dust resistant", "MagSafe technology", "Dolby Vision HDR video recording"],
            size: {length: 160.8, width: 78.1, height: 7.65},
            weight: 238,
            color: "Graphite",
            equipment: "USB-C to Lightning cable, Documentation"
        },
        guarantee: 365
    },
    {
        _id: UUID('5c7cd55d-14e5-40db-9828-fe2c681e1782'),
        label: "OnePlus 10 Pro",
        category: "mobile-phones",
        producer: "OnePlus",
        price: NumberDecimal('33999.00'),
        stock: 12,
        info: "The OnePlus 10 Pro is a premium smartphone offering powerful performance and sleek design.",
        specs: {
            CPU: "Snapdragon 8 Gen 2",
            RAM: 12,
            sdCard: null,
            storage: 256,
            display: "6.7\" Fluid AMOLED, 120Hz, HDR10+",
            mainCam: "48MP (wide) + 50MP (ultra-wide) + 8MP (telephoto) + 2MP (monochrome), " +
                     "Hasselblad Color Calibration",
            frontCam: "32MP, Auto HDR",
            sensors: ["Accelerometer", "Gyroscope", "Proximity", "Compass"],
            navigation: "GPS, GLONASS, Galileo, BDS",
            communication: ["5G", "LTE"],
            SIM: "Dual SIM (Nano-SIM and eSIM)",
            wireless: ["Bluetooth 5.2", "Wi-Fi 6E"],
            connectors: "USB Type-C 3.2",
            OS: "OxygenOS 12 based on Android 12",
            battery: "5000mAh, Warp Charge 80T",
            features: ["IP68 water/dust resistant", "In-display fingerprint sensor", "Stereo speakers"],
            size: {length: 163.2, width: 73.6, height: 8.7},
            weight: 206,
            color: "Morning Haze",
            equipment: "Warp Charge 80T adapter, USB Type-C cable, Quick start guide"
        },
        guarantee: 365
    },
    {
        _id: UUID('632e8927-3c43-42b5-aaf8-0587df28b0b0'),
        label: "Google Pixel 6 Pro",
        category: "mobile-phones",
        producer: "Google",
        price: 41999.00,
        stock: 18,
        info: "The Google Pixel 6 Pro is a flagship smartphone with advanced camera features and smooth performance.",
        specs: {
            CPU: "Google Tensor",
            RAM: 12,
            sdCard: null,
            storage: 256,
            display: "6.7\" Fluid AMOLED, 120Hz, HDR10+",
            mainCam: "50MP (wide) + 12MP (ultra-wide) + 48MP (telephoto), Night Sight, Super Res Zoom",
            frontCam: "11.1MP, Night Sight, Super Res Zoom",
            sensors: ["Face unlock", "Accelerometer", "Gyrometer", "Barometer", "Magnetometer"],
            navigation: "GPS, GLONASS, Galileo, QZSS",
            communication: ["5G", "LTE"],
            SIM: "Dual SIM (Nano-SIM and eSIM)",
            wireless: ["Bluetooth 5.2", "Wi-Fi 6E"],
            connectors: "USB Type-C 3.1",
            OS: "Android 12",
            battery: "5000mAh, Fast charging 30W",
            features: ["IP68 water/dust resistant", "Titan M2 security chip", "Google Assistant"],
            size: {length: 163.9, width: 75.9, height: 8.9},
            weight: 210,
            color: "Stormy Black",
            equipment: "USB-C to USB-C cable, SIM tool, Quick start guide"
        },
        guarantee: 365
    },

    // -- Tablets ("tablets") category items

    {
        _id: UUID('9e720a91-ea78-4008-b757-8e7ad6e9bba7'),
        label: "iPad Air (2023)",
        category: "tablets",
        producer: "Apple",
        price: NumberDecimal('27999.00'),
        stock: 8,
        info: "The iPad Air (2023) combines power and versatility in a sleek and lightweight design.",
        specs: {
            CPU: "Apple A15 Bionic chip",
            RAM: 8,
            sdCard: null,
            storage: 256,
            display: "10.9\" Liquid Retina display with True Tone and P3 wide color",
            mainCam: "12MP (wide), HDR, 4K video recording",
            frontCam: "12MP Ultra Wide, Center Stage",
            sensors: ["Touch ID", "Three-axis gyro", "Accelerometer", "Barometer"],
            navigation: "GPS, GLONASS, Galileo, QZSS",
            wireless: ["Bluetooth 5.0", "Wi-Fi 6"],
            connectors: "USB Type-C 3.1",
            OS: "iPadOS 15",
            battery: "28.6Whr, Up to 10 hours",
            features: ["Supports Apple Pencil (2nd generation)", "Supports Magic Keyboard and Smart Keyboard Folio"],
            size: {length: 247.6, width: 178.5, height: 6.1},
            weight: 458,
            color: "Space Gray",
            equipment: "USB-C to USB-C Cable, Documentation"
        },
        guarantee: 365
    },
    {
        _id: UUID('1e8a2ccf-2e25-4476-b250-d28721788269'),
        label: "Samsung Galaxy Tab S8+",
        category: "tablets",
        producer: "Samsung",
        price: NumberDecimal('37999.00'),
        stock: 6,
        info: "The Samsung Galaxy Tab S8+ is a premium Android tablet " +
              "with a stunning display and powerful performance.",
        specs: {
            CPU: "Snapdragon 8 Gen 2",
            RAM: 8,
            sdCard: "MicroSDXC (uses shared SIM slot), up to 1TB",
            storage: 256,
            display: "12.4\" Super AMOLED, 120Hz, HDR10+",
            mainCam: "13MP (wide), HDR, 4K video recording",
            frontCam: "8MP, HDR",
            sensors: ["Accelerometer", "Gyro", "Proximity", "Compass"],
            navigation: "GPS, GLONASS, BDS, GALILEO",
            wireless: ["Bluetooth 5.2", "Wi-Fi 6E"],
            connectors: "USB Type-C 3.2",
            OS: "Android 12 with One UI 4.1",
            battery: "10,090mAh",
            features: ["Fingerprint reader", "Fast charging 45W", "DeX mode support",
                       "S Pen included", "Quad speakers tuned by AKG"],
            size: {length: 285.5, width: 185, height: 5.7},
            weight: 575,
            color: "Mystic Black",
            equipment: "S Pen, USB-C to USB-C cable, Fast charger, Quick start guide"
        },
        guarantee: 365
    },
    {
        _id: UUID('2aba356e-d10e-44c4-8c80-a529c7013f85'),
        label: "Amazon Fire HD 10 (2022)",
        category: "tablets",
        producer: "Amazon",
        price: NumberDecimal('1999.00'),
        stock: 10,
        info: "The Amazon Fire HD 10 is a budget-friendly tablet offering a large display " +
              "and access to a wide range of content.",
        specs: {
            CPU: "MediaTek Helio P60T",
            RAM: 4,
            sdCard: "MicroSDXC, up to 1TB",
            storage: 64,
            display: "10.1\" 1080p Full HD",
            mainCam: "5MP (720p HD video recording)",
            frontCam: "2MP",
            sensors: ["Accelerometer", "Ambient light sensor"],
            navigation: "GPS, GLONASS",
            wireless: ["Bluetooth 5.0", "Dual-band Wi-Fi"],
            connectors: "USB Type-C 2.0",
            OS: "Fire OS 8 (based on Android)",
            battery: "6,300mAh, Up to 12 hours",
            features: ["Alexa hands-free", "Dolby Atmos audio", "Expandable storage up to 1TB"],
            size: {length: 247, width: 166, height: 9.2},
            weight: 465,
            color: "Black",
            equipment: "USB-C charging cable, Power adapter"
        },
        guarantee: 365
    },
    {
        _id: UUID('58d1f9f5-801c-4ee1-a367-c50141685f9f'),
        label: "Microsoft Surface Pro 8",
        category: "tablets",
        producer: "Microsoft",
        price: NumberDecimal('41999.00'),
        stock: 10,
        info: "The Microsoft Surface Pro 8 is a powerful tablet with the versatility of a laptop, " +
              "designed for professionals.",
        specs: {
            CPU: "Intel Core i7-1185G7",
            RAM: 16,
            sdCard: null,
            storage: 512,
            display: "13\" PixelSense Flow display, 120Hz",
            mainCam: "16MP (rear), 4K video",
            frontCam: "5MP (front), 1080p video",
            sensors: ["Ambient light sensor", "Accelerometer", "Gyroscope", "Magnetometer"],
            navigation: null,
            wireless: ["Bluetooth 5.0", "Wi-Fi 6E"],
            connectors: "USB Type-C 4.0",
            OS: "Windows 11 Pro",
            battery: "56.5Whr, Up to 16 hours",
            features: ["Windows Hello", "Surface Pen support"],
            size: {length: 287, width: 208, height: 8.5},
            weight: 803,
            color: "Platinum",
            equipment: "Surface Pen, Power supply, Quick start guide"
        },
        guarantee: 365
    },

    // -- Smartwatches ("smartwatches") category items

    {
        _id:  UUID('f771ffbd-66b0-4d19-99f7-974a9d047c87'),
        label: "Apple Watch Series 7",
        category: "smartwatches",
        producer: "Apple",
        price: NumberDecimal('14999.00'),
        stock: 15,
        info: "The Apple Watch Series 7 offers advanced health monitoring and fitness tracking in a sleek design.",
        specs: {
            display: "LTPO OLED Retina display",
            sensors: ["Blood oxygen sensor", "ECG app", "Optical heart sensor",
                      "Accelerometer", "Gyroscope", "Ambient light sensor"],
            functions: ["ECG", "Fall detection", "Fitness tracking", "Sleep tracking"],
            wireless: ["Bluetooth 5.0", "Wi-Fi 802.11b/g/n 2.4GHz"],
            navigation: "GPS, GLONASS, Galileo, QZSS",
            OS: "watchOS 8",
            hosts: ["iPhone 6s or later with iOS 15 or later"],
            battery: "Up to 18 hours",
            charging: ["Magnetic charging", "USB Power Adapter"],
            features: ["Water resistant up to 50 meters", "Always-On Retina display", "Siri"],
            protection: ["Water resistant (50m)", "Dust resistant"],
            size: {length: 41, width: 34, height: 10.7},
            shape: "Rectangular",
            weight: 32,
            color: "Midnight Aluminum",
            equipment: "Magnetic charging cable, USB power adapter, Documentation"
        },
        guarantee: 365
    },
    {
        _id: UUID('8f00c00d-c3dc-480a-a8c1-77341aa613ef'),
        label: "Samsung Galaxy Watch 4",
        category: "smartwatches",
        producer: "Samsung",
        price: NumberDecimal('9999.00'),
        stock: 12,
        info: "The Samsung Galaxy Watch 4 combines style with advanced health and fitness features " +
              "for a comprehensive smartwatch experience.",
        specs: {
            display: "1.19\" AMOLED, Corning Gorilla Glass DX",
            sensors: ["Heart rate monitor", "ECG", "Accelerometer", "Gyroscope", "Barometer", "Ambient light sensor"],
            functions: ["Advanced sleep tracking", "Fitness tracking", "ECG", "Blood oxygen monitoring"],
            wireless: ["Bluetooth 5.0", "Wi-Fi 802.11 b/g/n"],
            navigation: "GPS, GLONASS, Galileo, BDS",
            OS: "Wear OS powered by Samsung",
            battery: "Up to 40 hours",
            charging: ["Wireless charging", "Magnetic charging"],
            features: ["Samsung Pay", "Bixby"],
            protection: ["5ATM", "MIL-STD-810G"],
            size: {length: 44, width: 44, height: 10.9},
            shape: "Round",
            weight: 30,
            color: "Black",
            equipment: "Wireless charging pad, USB cable, Quick start guide"
        },
        guarantee: 365
    },
    {
        _id: UUID('5e29b0e0-d88f-4206-bd9c-eb6dc192920c'),
        label: "Fitbit Sense",
        category: "smartwatches",
        producer: "Fitbit",
        price: NumberDecimal('8999.00'),
        stock: 10,
        info: "The Fitbit Sense is an advanced health smartwatch with stress management tools " +
              "and built-in GPS for fitness tracking.",
        specs: {
            display: "1.58\" AMOLED, Corning Gorilla Glass 3",
            sensors: ["ECG", "EDA sensor", "Skin temperature sensor", "Heart rate monitor",
                      "Accelerometer", "Gyroscope", "Ambient light sensor"],
            functions: ["ECG", "Stress management score", "Sleep tracking", "Built-in GPS"],
            wireless: ["Bluetooth 5.0", "Wi-Fi 802.11 b/g/n"],
            navigation: null,
            OS: "Fitbit OS",
            battery: "Up to 6 days",
            charging: ["Magnetic charging cable"],
            features: ["Fitbit Pay", "Voice assistant (Amazon Alexa or Google Assistant)"],
            protection: ["5ATM"],
            size: {length: 40.5, width: 40.5, height: 12.4},
            shape: "Round",
            weight: 50,
            color: "Carbon/Graphite Stainless Steel",
            equipment: "Magnetic charging cable, Quick start guide"
        },
        guarantee: 365
    },
    {
        _id: UUID('09007b6a-bd66-4512-adf4-5af53002e477'),
        label: "Garmin Venu 2 Plus",
        category: "smartwatches",
        producer: "Garmin",
        price: NumberDecimal('14999.00'),
        stock: 15,
        info: "The Garmin Venu 2 Plus is a premium GPS smartwatch with advanced health monitoring and music features.",
        specs: {
            display: "1.3\" AMOLED, Corning Gorilla Glass DX",
            sensors: ["Heart rate monitor", "Pulse Ox", "Body Battery energy monitor",
                      "Accelerometer", "Gyroscope", "Barometric altimeter",
                      "Compass", "Thermometer"],
            wireless: ["Bluetooth", "Wi-Fi"],
            navigation: "GPS, GLONASS, Galileo",
             OS: "Garmin OS",
            battery: "Up to 11 days",
            charging: ["USB charging cable"],
            features: ["Music storage and playback", "Advanced sleep monitoring", "Garmin Pay"],
            protection: ["5ATM", "MIL-STD-810G"],
            size: {length: 45.4, width: 45.4, height: 12.2},
            shape: "Round",
            weight: 50.5,
            color: "Granite Blue",
            equipment: "USB charging cable, Documentation"
        },
        guarantee: 365
    }
]);
